### ISSUE TITLE
get_market_history is nor working 

### ISSUE THREAD

**Issue by kzlinguistics** [Kalshi/kalshi-python#11]
get_series and get_event both works fine for me but get_market_history keeps on returning ApiException: (400)
citing HTTP response body: b'{"error":{"code":"invalid_credentials","message":"invalid credentials","service":"auth"}}'

**Comment by Chisom2K** [comment]
Hey @kzlinguistics, i'm having the same problem, i'm just trying to test out the starter code, how were you able to fix this?

**Comment by LYK-CC** [comment]
same
