### ISSUE TITLE
get_market_orderbook() raises error for orderbooks with 0 orders for "yes" or for "no"

### ISSUE THREAD

**Issue by DecibillyJoel** [Kalshi/kalshi-python#2]
It tries to create an OrderBook with the "yes" or "no" field set to None, which raises this ValueError:
https://github.com/Kalshi/kalshi-python/blob/main/kalshi_python/models/order_book.py#L90

**Comment by hsousak** [comment]
This is fixed in the latest release @DecibillyJoel.

https://pypi.org/project/kalshi-python/2.0.0/

Thanks for reporting, sorry for the delay.
